// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBNWum07MMpO3t8zLImdqGbxlc59Zm9bQ',
    appId: '1:165304721858:web:fa1497a48586710837b65b',
    messagingSenderId: '165304721858',
    projectId: 'datastore-b6c54',
    authDomain: 'datastore-b6c54.firebaseapp.com',
    storageBucket: 'datastore-b6c54.firebasestorage.app',
    measurementId: 'G-YE4H07PN87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgzjtYnFydIOMSv3mXXoq4Mdm2xe5g3no',
    appId: '1:165304721858:android:2cff4b36c1cdcb1f37b65b',
    messagingSenderId: '165304721858',
    projectId: 'datastore-b6c54',
    storageBucket: 'datastore-b6c54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeZKK2u0OJrIe9iTt5u1xxJ8LV8aYbQ9s',
    appId: '1:165304721858:ios:812af460033a6eec37b65b',
    messagingSenderId: '165304721858',
    projectId: 'datastore-b6c54',
    storageBucket: 'datastore-b6c54.firebasestorage.app',
    iosBundleId: 'com.example.firebasefirestore',
  );
}
